-- =============================================================================
-- Migration: 000020_therapist_extended_profile (UP)
-- Purpose  : Storage abstraction + therapist extended customer-facing profile.
--            Implements ADR 0011 §2.3 exactly:
--              1. Rename therapist.photo_url → therapist.photo_key.
--                 Drop the old inline CHECK (auto-named therapist_photo_url_check
--                 by migration 000003) before the rename so no dangling
--                 constraint metadata remains after the column is gone.
--                 Null stranded full-URL values — they cannot serve as opaque
--                 storage keys; admin must re-upload (dev seeds only affected,
--                 §2.3.1).
--                 Add a tighter length constraint (≤ 512) to match key semantics.
--
--              2. Add therapist.height_cm — SMALLINT NOT NULL, CHECK 100–250.
--                 Placeholder 160 for existing rows (within the valid range so
--                 the CHECK constraint is immediately satisfiable; ADR 0011
--                 §2.3.2 — admin UI flags placeholder rows for curation).
--
--              3. Add therapist.weight_kg — SMALLINT NOT NULL, CHECK 30–250.
--                 Placeholder 60 for existing rows.
--
--              4. Add therapist.build — TEXT NOT NULL,
--                 CHECK IN ('langsing','sedang','atletis','tegap').
--                 Placeholder 'sedang' for existing rows.
--
-- Pattern note: this migration is one-shot (not guarded for idempotency on
-- re-run), matching the convention of migrations 000015–000019.
-- Migrations 1→20 form a clean chain on any environment.
--
-- Cross-agent: go-expert must update TherapistRequest DTO (add height_cm,
-- weight_kg, build; keep photo_key out of the JSON body per §2.3.2) and
-- rename the GORM column tag from photo_url → photo_key.
-- nextjs-expert must surface the three new fields in the therapist form.
--
-- Reference: docs/DECISIONS/0011-storage-abstraction-and-therapist-profile.md
-- =============================================================================

-- ---------------------------------------------------------------------------
-- STEP 1: Drop the old inline CHECK on photo_url before renaming.
--
-- Migration 000003 defined the column as:
--   photo_url TEXT NULL CHECK (photo_url IS NULL OR char_length(photo_url) <= 2048)
-- PostgreSQL auto-names an anonymous inline CHECK constraint as
-- <table>_<column>_check — i.e. therapist_photo_url_check.
-- We must drop it now; after the RENAME it would reference a non-existent
-- column name and cannot be dropped by the old name.
-- ---------------------------------------------------------------------------
ALTER TABLE therapist
    DROP CONSTRAINT IF EXISTS therapist_photo_url_check;

-- ---------------------------------------------------------------------------
-- STEP 2: Rename photo_url → photo_key.
--
-- RENAME preserves any B-tree indexes on the column and adjusts their
-- internal column references automatically. There are no named indexes on
-- photo_url in migrations 000003–000019, so this is clean.
-- ---------------------------------------------------------------------------
ALTER TABLE therapist
    RENAME COLUMN photo_url TO photo_key;

-- ---------------------------------------------------------------------------
-- STEP 3: Null out stranded full-URL values.
--
-- Any existing photo_url value is a full HTTP(S) URL (e.g.
-- "https://…/uploads/…"). These are not opaque storage keys and cannot be
-- resolved by Storage.URL(). Null them so the column is in a known-clean
-- state. Admins re-upload via the new POST …/therapists/:id/photo endpoint.
-- Affects only dev-seed rows in acme-spa (ADR 0011 §2.3.1).
-- ---------------------------------------------------------------------------
UPDATE therapist
    SET photo_key = NULL
    WHERE photo_key IS NOT NULL;

-- ---------------------------------------------------------------------------
-- STEP 4: Add length constraint for key semantics (≤ 512 chars).
--
-- Storage keys generated by the upload pipeline are
-- "therapists/{uuid}/{16-hex}.{ext}" — well under 512 characters.
-- A URL-length cap (2048) would be misleading given the new semantics.
-- ---------------------------------------------------------------------------
ALTER TABLE therapist
    ADD CONSTRAINT therapist_photo_key_length
        CHECK (photo_key IS NULL OR char_length(photo_key) <= 512);

-- ---------------------------------------------------------------------------
-- STEP 5: Add height_cm.
--
-- Add as nullable first, populate existing rows with the placeholder value
-- (160 — within the valid range 100–250 so the subsequent CHECK does not
-- fail), promote to NOT NULL, add the CHECK constraint, then drop the
-- DEFAULT so new rows must supply a real value.
-- ---------------------------------------------------------------------------
ALTER TABLE therapist
    ADD COLUMN IF NOT EXISTS height_cm SMALLINT NULL DEFAULT 160;

UPDATE therapist
    SET height_cm = 160
    WHERE height_cm IS NULL;

ALTER TABLE therapist
    ALTER COLUMN height_cm SET NOT NULL;

ALTER TABLE therapist
    ADD CONSTRAINT therapist_height_cm_check
        CHECK (height_cm BETWEEN 100 AND 250);

ALTER TABLE therapist
    ALTER COLUMN height_cm DROP DEFAULT;

-- ---------------------------------------------------------------------------
-- STEP 6: Add weight_kg.
--
-- Same pattern as height_cm. Placeholder 60 is within the valid range
-- 30–250.
-- ---------------------------------------------------------------------------
ALTER TABLE therapist
    ADD COLUMN IF NOT EXISTS weight_kg SMALLINT NULL DEFAULT 60;

UPDATE therapist
    SET weight_kg = 60
    WHERE weight_kg IS NULL;

ALTER TABLE therapist
    ALTER COLUMN weight_kg SET NOT NULL;

ALTER TABLE therapist
    ADD CONSTRAINT therapist_weight_kg_check
        CHECK (weight_kg BETWEEN 30 AND 250);

ALTER TABLE therapist
    ALTER COLUMN weight_kg DROP DEFAULT;

-- ---------------------------------------------------------------------------
-- STEP 7: Add build.
--
-- Four-value controlled vocabulary. TEXT + CHECK is used in preference to a
-- native Postgres ENUM so values can be added via a non-destructive migration
-- (ALTER TABLE ... ADD CONSTRAINT with a new CHECK) rather than requiring
-- ALTER TYPE, which blocks concurrent reads in older Postgres versions.
-- Placeholder 'sedang' is the most common build category and is within the
-- allowed set, so the CHECK is immediately satisfied.
-- ---------------------------------------------------------------------------
ALTER TABLE therapist
    ADD COLUMN IF NOT EXISTS build TEXT NULL DEFAULT 'sedang';

UPDATE therapist
    SET build = 'sedang'
    WHERE build IS NULL;

ALTER TABLE therapist
    ALTER COLUMN build SET NOT NULL;

ALTER TABLE therapist
    ADD CONSTRAINT therapist_build_check
        CHECK (build IN ('langsing', 'sedang', 'atletis', 'tegap'));

ALTER TABLE therapist
    ALTER COLUMN build DROP DEFAULT;

-- ---------------------------------------------------------------------------
-- COMMENTS
-- ---------------------------------------------------------------------------
COMMENT ON COLUMN therapist.photo_key IS
    'Opaque storage key produced by Storage.Upload() (ADR 0011 §2.1). '
    'Format: "therapists/{therapist_id}/{16-hex}.{ext}". '
    'Never contains scheme or host — controllers call Storage.URL(ctx, key) '
    'at read time to resolve to a public URL. '
    'NULL = no photo uploaded yet.';

COMMENT ON COLUMN therapist.height_cm IS
    'Therapist height in whole centimetres. Customer-visible in Phase 5 '
    'booking picker. Valid range 100–250. Placeholder rows from migration '
    '000020 carry the value 160; admin UI flags these for curation.';

COMMENT ON COLUMN therapist.weight_kg IS
    'Therapist weight in whole kilograms. Customer-visible in Phase 5 '
    'booking picker. Valid range 30–250. Placeholder rows from migration '
    '000020 carry the value 60; admin UI flags these for curation.';

COMMENT ON COLUMN therapist.build IS
    'Body build category. Customer-visible in Phase 5 booking picker. '
    'Controlled vocabulary: langsing | sedang | atletis | tegap. '
    'Stored as TEXT + CHECK (not a native ENUM) so adding values in future '
    'migrations does not require ALTER TYPE.';
